[project]
    dependencies    = [
    "sqlglot>=28.6.0",
]
    description     = "Polars syntax for SQL"
    name            = "pql"
    readme          = "README.md"
    requires-python = ">=3.13"
    version         = "0.1.0"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
